apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: selfhealtestapp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  destination:
    namespace: argocdappdemo
    server: 'https://kubernetes.default.svc'
  source:
    path: 0-Demo_Files/Nginx_Deployment
    repoURL: 'https://github.com/hienpham94/ArgoCD-Complete-Master-Course.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
